<a href="https://colab.research.google.com/github/judithwang021/judith-6070/blob/main/WeeklyModules/Week05/Assignment5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import statsmodels.formula.api as sm
import statsmodels.api as se
import seaborn as sns
import datetime as dt
from sklearn.linear_model import LinearRegression
from scipy import stats
from io import StringIO
import itertools
from pathlib import Path

pd.set_eng_float_format(accuracy=3, use_eng_prefix=True)
pd.set_option('display.float_format', lambda x: '%.2f' % x)

from google.colab import userdata
import os
import subprocess

github_token = userdata.get('Git_Key') #Retrieve secret key for user
owner = 'judithwang021' # Replace with the GitHub repository owner
repository = 'judith-6070' # Replace with the GitHub repository name

clone_url = f'https://x-access-token:{github_token}@github.com/{owner}/{repository}.git'

# Clone the repository
import subprocess
subprocess.run(['git', 'clone', clone_url])

# Navigate into the cloned repository directory (optional, but often useful)
os.chdir(repository)
print(f"Changed directory to: {os.getcwd()}")

#!git clone https://github.com/"owner"/"repository".git for public repositories

Changed directory to: /content/judith-6070/judith-6070

In [9]:
path1 = Path("/content/judith-6070/data/aapl.csv")
path2 = Path("/content/judith-6070/data/amzn.csv")
path3 = Path("/content/judith-6070/data/nflx.csv")
path4 = Path("/content/judith-6070/data/fb.csv")
path5 = Path("/content/judith-6070/data/goog.csv")
aapl = pd.read_csv(path1)
amzn = pd.read_csv(path2)
nflx = pd.read_csv(path3)
fb = pd.read_csv(path4)
goog = pd.read_csv(path5)

In [10]:
aapl["ticker"] = "AAPL"
amzn["ticker"] = "AMZN"
nflx["ticker"] = "NFLX"
fb["ticker"] = "FB"
goog["ticker"] = "GOOG"

In [11]:
stock = pd.concat([aapl, amzn, nflx, fb, goog])
stock.to_csv("/content/judith-6070/data/faanf.csv")

In [12]:
stock = pd.read_csv("/content/judith-6070/data/faanf.csv")
stock["date"] = pd.to_datetime(stock["date"])
stock["volume"] = stock["volume"].astype(int)
stock = stock.sort_values(by=["date", "ticker"])
stock = stock.drop(columns=["Unnamed: 0"], errors="ignore")
stock.head()

           date    open    high     low   close    volume ticker
0    2018-01-02  166.93  169.03  166.04  168.99  25555934   AAPL
251  2018-01-02 1172.00 1190.00 1170.51 1189.01   2694494   AMZN
753  2018-01-02  177.68  181.58  177.55  181.42  18151903     FB
1004 2018-01-02 1048.34 1066.94 1045.23 1065.00   1237564   GOOG
502  2018-01-02  196.10  201.65  195.42  201.07  10966889   NFLX

In [13]:
top7 = stock.nlargest(7, "volume")
top7

          date   open   high    low  close     volume ticker
895 2018-07-26 174.89 180.13 173.75 176.26  169803668     FB
806 2018-03-20 167.47 170.20 161.95 168.15  129851768     FB
810 2018-03-26 160.82 161.10 149.02 160.06  126116634     FB
807 2018-03-21 164.80 173.40 163.30 169.39  106598834     FB
182 2018-09-21 219.07 219.65 215.61 215.98   96246748   AAPL
245 2018-12-21 156.19 157.48 148.99 150.09   95744384   AAPL
212 2018-11-02 207.93 212.00 203.84 205.88   91328654   AAPL

In [14]:
stock2 = stock.melt(id_vars= ["date", "ticker"],
                    var_name= "variables",
                    value_name= "values")
stock2.head(10)

        date ticker variables  values
0 2018-01-02   AAPL      open  166.93
1 2018-01-02   AMZN      open 1172.00
2 2018-01-02     FB      open  177.68
3 2018-01-02   GOOG      open 1048.34
4 2018-01-02   NFLX      open  196.10
5 2018-01-03   AAPL      open  169.25
6 2018-01-03   AMZN      open 1188.30
7 2018-01-03     FB      open  181.88
8 2018-01-03   GOOG      open 1064.31
9 2018-01-03   NFLX      open  202.05