<a href="https://colab.research.google.com/github/judithwang021/judith-6070/blob/main/WeeklyModules/Week04/Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
parsed = pd.read_csv('/content/drive/MyDrive/parsed.csv')

In [ ]:
japan_mb = parsed[(parsed['parsed_place'] == 'Japan') &
                  (parsed['magType'] == 'mb')]
japan_mb['mag'].quantile(0.95)

np.float64(4.9)

The 95th percentile of earthquake magnitude in Japan using magType of 'mb' is 4.9.

In [ ]:
indonesia = parsed[(parsed['parsed_place'] == 'Indonesia')]
indonesia['tsunami'].mean()

np.float64(0.23129251700680273)

The percentage of earthquakes in Indonesia that were coupled with tsunamis is about 23.13%.

In [ ]:
nevada = parsed[parsed['parsed_place'] == 'Nevada']
nevada.describe()

,cdi,dmin,felt,gap,mag,mmi,nst,rms,sig,time,tsunami,tz,updated
count,15.000000,681.000000,15.000000,681.000000,681.000000,1.00,681.000000,681.000000,681.000000,6.810000e+02,681.0,681.0,6.810000e+02
mean,2.440000,0.166199,2.400000,153.668120,0.500073,2.84,12.618209,0.151986,10.970631,1.538314e+12,0.0,-480.0,1.538402e+12
std,0.501142,0.166228,4.626013,68.735302,0.696710,NaN,9.866963,0.084662,19.607150,5.965637e+08,0.0,0.0,6.010951e+08
min,2.000000,0.001000,1.000000,29.140000,-0.500000,2.84,3.000000,0.000500,0.000000,1.537247e+12,0.0,-480.0,1.537307e+12
25%,2.000000,0.053000,1.000000,97.380000,-0.100000,2.84,6.000000,0.106900,0.000000,1.537854e+12,0.0,-480.0,1.537928e+12
50%,2.200000,0.112000,1.000000,149.140000,0.400000,2.84,10.000000,0.146300,2.000000,1.538280e+12,0.0,-480.0,1.538428e+12
75%,2.900000,0.233000,1.000000,199.720000,0.900000,2.84,16.000000,0.187100,12.000000,1.538821e+12,0.0,-480.0,1.538878e+12
max,3.300000,1.414000,19.000000,355.910000,2.900000,2.84,61.000000,0.863400,129.000000,1.539461e+12,0.0,-480.0,1.539483e+12

In [ ]:
ring_of_fire = [
    'Bolivia',
    'Chile',
    'Ecuador',
    'Peru',
    'Costa Rica',
    'Guatemala',
    'Mexico',
    'Japan',
    'Philippines',
    'Indonesia',
    'New Zealand',
    'Canada',
    'Fiji',
    'Alaska',
    'Washington',
    'California',
    'Russia',
    'Taiwan',
    'Tonga',
    'Kermadec Islands']
len(ring_of_fire)

20

In [ ]:
antarctic = parsed['parsed_place'].str.contains('Antarctic', na=False)
antarctic
parsed.loc[antarctic, 'parsed_place'].value_counts()

parsed_place
Pacific-Antarctic Ridge           3
Western Indian-Antarctic Ridge    1
Name: count, dtype: int64

In [ ]:
parsed['ring_of_fire'] = (parsed['parsed_place'].isin(ring_of_fire) |
                          parsed['parsed_place'].str.contains('Antarctic', na=False))
parsed['ring_of_fire'].value_counts()

ring_of_fire
True     7188
False    2144
Name: count, dtype: int64

In [ ]:
inside = parsed['ring_of_fire'].sum()
outside = (~parsed['ring_of_fire']).sum()
print(inside)
print(outside)

7188
2144

In [ ]:
inside_earthquakes = parsed[parsed['ring_of_fire']]
print(inside_earthquakes['tsunami'].sum())

45