<a href="https://colab.research.google.com/github/judithwang021/judith-6070/blob/main/WeeklyModules/Week04/Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import statsmodels.formula.api as sm
import statsmodels.api as se
import seaborn as sns
import datetime as dt
from sklearn.linear_model import LinearRegression
from scipy import stats
from io import StringIO
import itertools
from pathlib import Path

pd.set_eng_float_format(accuracy=3, use_eng_prefix=True)
pd.set_option('display.float_format', lambda x: '%.2f' % x)

from google.colab import userdata
import os

github_token = userdata.get('github_token')
owner = 'judithwang021' # Replace with the GitHub repository owner
repository = 'judith-6070' # Replace with the GitHub repository name

clone_url = f'https://{github_token}@github.com/{owner}/{repository}.git'

# Clone the repository
import subprocess
subprocess.run(['git', 'clone', clone_url])

# Navigate into the cloned repository directory (optional, but often useful)
os.chdir(repository)
print(f"Changed directoGit_HUBry to: {os.getcwd()}")

Changed directoGit_HUBry to: /content/judith-6070/judith-6070/judith-6070/judith-6070

In [31]:
file_path = Path("/content/judith-6070/data/parsed.csv")
parsed = pd.read_csv(file_path)

In [32]:
japan_mb = parsed[(parsed['parsed_place'] == 'Japan') &
                  (parsed['magType'] == 'mb')]
japan_mb['mag'].quantile(0.95)

np.float64(4.9)

The 95th percentile of earthquake magnitude in Japan using magType of 'mb' is 4.9.

In [33]:
indonesia = parsed[(parsed['parsed_place'] == 'Indonesia')]
indonesia['tsunami'].mean()

np.float64(0.23129251700680273)

The percentage of earthquakes in Indonesia that were coupled with tsunamis is about 23.13%.

In [34]:
nevada = parsed[parsed['parsed_place'] == 'Nevada']
nevada.describe()

,cdi,dmin,felt,gap,mag,mmi,nst,rms,sig,time,tsunami,tz,updated
count,15.00,681.00,15.00,681.00,681.00,1.00,681.00,681.00,681.00,681.00,681.00,681.00,681.00
mean,2.44,0.17,2.40,153.67,0.50,2.84,12.62,0.15,10.97,1538313805281.28,0.00,-480.00,1538401660548.00
std,0.50,0.17,4.63,68.74,0.70,NaN,9.87,0.08,19.61,596563746.20,0.00,0.00,601095107.44
min,2.00,0.00,1.00,29.14,-0.50,2.84,3.00,0.00,0.00,1537247268525.00,0.00,-480.00,1537306663881.00
25%,2.00,0.05,1.00,97.38,-0.10,2.84,6.00,0.11,0.00,1537854384162.00,0.00,-480.00,1537927505348.00
50%,2.20,0.11,1.00,149.14,0.40,2.84,10.00,0.15,2.00,1538279862199.00,0.00,-480.00,1538427614580.00
75%,2.90,0.23,1.00,199.72,0.90,2.84,16.00,0.19,12.00,1538821434704.00,0.00,-480.00,1538877980517.00
max,3.30,1.41,19.00,355.91,2.90,2.84,61.00,0.86,129.00,1539461038285.00,0.00,-480.00,1539482718719.00

In [35]:
ring_of_fire = [
    'Bolivia',
    'Chile',
    'Ecuador',
    'Peru',
    'Costa Rica',
    'Guatemala',
    '^Mexico',
    'Japan',
    'Philippines',
    'Indonesia',
    'New Zealand',
    'Canada',
    'Fiji',
    'Alaska',
    'Washington',
    'California',
    'Russia',
    'Taiwan',
    'Tonga',
    'Kermadec Islands']
len(ring_of_fire)

20

In [36]:
antarctic = parsed['parsed_place'].str.contains('Antarctic', na=False)
antarctic
parsed.loc[antarctic, 'parsed_place'].value_counts()

parsed_place
Pacific-Antarctic Ridge           3
Western Indian-Antarctic Ridge    1
Name: count, dtype: int64

In [37]:
parsed['ring_of_fire'] = (parsed['parsed_place'].isin(ring_of_fire) |
                          parsed['parsed_place'].str.contains('Antarctic', na=False))
parsed[['ring_of_fire', 'parsed_place']]

      ring_of_fire parsed_place
0             True   California
1             True   California
2             True   California
3             True   California
4             True   California
...            ...          ...
9327          True   California
9328          True   California
9329         False  Puerto Rico
9330          True   California
9331          True   California

[9332 rows x 2 columns]

In [38]:
parsed['ring_of_fire'].value_counts()

ring_of_fire
True     7150
False    2182
Name: count, dtype: int64

In [39]:
inside = parsed['ring_of_fire'].sum()
outside = (~parsed['ring_of_fire']).sum()
print(inside)
print(outside)

7150
2182

In [40]:
inside_earthquakes = parsed[parsed['ring_of_fire']]
print(inside_earthquakes['tsunami'].sum())

44

In [41]:
parsed.loc[parsed['ring_of_fire'], 'tsunami'].sum()

np.int64(44)